In [ ]:
import numpy as np
vct=np.arange(10, 50,1)


In [ ]:
array_3x3 = np.arange(9).reshape(3, 3)
print(array_3x3)


[[0 1 2]
 [0 0 0]
 [0 0 0]]


In [31]:
arr=np.zeros((3,3), dtype=int)
i=0
while i<3:
    arr[i, i]=1
    i=i+1
print(arr)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [42]:
import random
lst=[random.randrange(1, 9) for i in range(27)]

arr=np.array(lst)
fina=arr.reshape(3, 3, 3)
print(fina)


[[[6 4 3]
  [1 6 4]
  [2 6 8]]

 [[5 1 6]
  [3 3 3]
  [4 1 6]]

 [[5 4 8]
  [4 2 3]
  [8 2 2]]]


In [ ]:

arr=np.random.randint(low=1, high=9, size=(10, 10))
maxi=arr.max()
mini=arr.min()
print(maxi)
print(mini)


8
1


In [55]:
arr=np.random.randint(low=0, high=100, size=(30))
print(arr.mean())


50.266666666666666


In [66]:
lst=[random.randint(1, 9) for i in range(25)]
arr=np.array(lst).reshape(5, 5)
print(arr)
mini=arr.min()
maxi=arr.max()
norm_arr=(arr-mini)/(maxi-mini)
print(norm_arr)


[[8 2 3 2 1]
 [7 5 1 5 3]
 [4 4 6 7 4]
 [9 7 6 9 1]
 [3 3 9 4 5]]
[[0.875 0.125 0.25  0.125 0.   ]
 [0.75  0.5   0.    0.5   0.25 ]
 [0.375 0.375 0.625 0.75  0.375]
 [1.    0.75  0.625 1.    0.   ]
 [0.25  0.25  1.    0.375 0.5  ]]


In [ ]:
arr1=np.random.randint(1, 9, (5,3))
arr2=np.random.randint(1, 9, (3, 2))
print(arr1)
print(arr2)
print(arr1@arr2)
print(np.dot(arr1, arr2))


[[5 4 4]
 [1 3 2]
 [6 8 2]
 [5 5 5]
 [5 6 5]]
[[2 3]
 [5 7]
 [2 8]]
[[38 75]
 [21 40]
 [56 90]
 [45 90]
 [50 97]]
[[38 75]
 [21 40]
 [56 90]
 [45 90]
 [50 97]]


In [ ]:
arr1=np.random.randint(0, 99, (3, 3))
arr2=np.random.randint(0, 99, (3, 3))
print(arr1)
print(arr2)
prod=np.dot(arr1, arr2)
print(prod)


[[ 7  8 68]
 [72 57 78]
 [86  1 28]]
[[70 55 30]
 [90 17 64]
 [88 37 42]]
[[ 7194  3037  3578]
 [17034  7815  9084]
 [ 8574  5783  3820]]


In [ ]:
arr1=np.random.randint(0, 99, (4, 4))
arr2=arr1.transpose()
print(arr2)



[[60 91 12 15]
 [36 85 46 97]
 [71  6 88 91]
 [49 89 33 87]]
[[60 36 71 49]
 [91 85  6 89]
 [12 46 88 33]
 [15 97 91 87]]


In [ ]:
arr1=np.random.randint(0, 99, (3, 3))
deter=np.linalg.det(arr1)
print(arr1)
print(deter)


[[25 42 53]
 [83 71 68]
 [49 70 44]]
69202.99999999999


In [ ]:
A=np.random.randint(0, 9, (3, 4))
B=np.random.randint(0, 9, (4, 3))
prod=np.dot(A, B)
print(prod)


[[49 52 68]
 [29 20 28]
 [29 56 55]]


In [96]:
A=np.random.randint(0, 9, (3, 3))
B=np.random.randint(0, 9, (3))
print(np.dot(A, B))


[20 14 19]


In [115]:
A = np.array([[2, 1, 3],
              [1, 2, 3],
              [3, 3, 1]])
b = np.array([1, 2, 3])

print(b)
print(A)
x=np.linalg.solve(A, b)
print(x)



[1 2 3]
[[2 1 3]
 [1 2 3]
 [3 3 1]]
[1.11022302e-16 1.00000000e+00 2.22044605e-17]


In [124]:
a=np.array(range(25)).reshape(5, 5)
roww=a.sum(axis=1)
colu=a.sum(axis=0)
print(a)
print(roww)
print(colu)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 10  35  60  85 110]
[50 55 60 65 70]
