In [35]:
import numpy as np
def conv(faren: float):
    return (faren-32)*5/9
nconv=np.vectorize(conv)
fars=np.array([32, 68, 100, 212, 77])
conv(fars)


array([  0.        ,  20.        ,  37.77777778, 100.        ,
        25.        ])

In [36]:
def numpow(number:int, power:int):
    return number**power
vnumpow=np.vectorize(numpow)
nums=[2, 3, 4, 5]
pows=[1, 2, 3, 4]
vnumpow(nums, pows)


array([  2,   9,  64, 625])

In [37]:
A=np.array([
    [4, 5, 6], 
    [3, -1, 1],
    [2, 1, -2]
])
b=np.array([7, 4, 5])
ans=np.linalg.inv(A)@b
print(ans)


[ 1.7027027   0.62162162 -0.48648649]


In [38]:
A=np.array([
    [10, -2, 3], 
    [-2, 8, -1],
    [3, -1, 6]
])
b=np.array([12, -5, 15])
ans=np.linalg.inv(A)@b
print(ans)


[ 0.48963731 -0.2253886   2.21761658]


In [39]:
from PIL import Image
with Image.open('images/birds.jpg') as img:
    img_arr=np.array(img)


In [40]:
flip_arr=np.flip(img_arr, axis=0)
flip_img=Image.fromarray(flip_arr)
flip_img.save('images/flipped_image.png')


In [41]:
import random
nois_arr=img_arr+random.randint(0, 50)
nois_img=Image.fromarray(nois_arr)
nois_img.save('images/noisy_image.png')


In [42]:
br_arr=img_arr
br_arr[:,:,0]=br_arr[:,:,0]+40
br_arr=np.clip(br_arr, 0, 255)
br_img=Image.fromarray(br_arr)
br_img.save('images/bright_image.png')


In [44]:
with Image.open('images/birds.jpg') as img:
    img_arr=np.array(img)
mask_arr=img_arr
mask_arr[310:410, 310:410, :]=0
mask_img=Image.fromarray(mask_arr)
mask_img.save('images/masked_image.png')
